# Generated by Django 3.1 on 2020-11-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_Key', models.PositiveIntegerField()),
                ('Reference_ID', models.CharField(max_length=10)),
                ('Date', models.DateField(verbose_name='Date Occured')),
                ('Is_actual', models.BooleanField(default=True)),
                ('Zone_colour', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Zone',
                'ordering': ['-Date', 'Zone_colour'],
                'unique_together': {('Date', 'Reference_ID', 'Is_actual')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('State_Name', models.CharField(max_length=50)),
                ('Country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country')),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('District_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('District_Name', models.CharField(max_length=50)),
                ('State_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
            ],
            options={
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_Key', models.PositiveIntegerField()),
                ('Reference_ID', models.CharField(max_length=10)),
                ('Date', models.DateField(verbose_name='Date Occured')),
                ('Daily_infected', models.PositiveIntegerField(null=True)),
                ('Daily_deaths', models.PositiveIntegerField(null=True)),
                ('Daily_recoveries', models.PositiveIntegerField(null=True)),
                ('Respiratory_aid', models.PositiveIntegerField(null=True)),
                ('No_of_patient_in_ICU', models.PositiveIntegerField(null=True)),
                ('Total_infected', models.PositiveIntegerField(null=True)),
                ('Total_deaths', models.PositiveIntegerField(null=True)),
                ('Total_recoveries', models.PositiveIntegerField(null=True)),
                ('Active_cases', models.PositiveIntegerField(null=True)),
                ('Total_tests', models.PositiveIntegerField(null=True)),
                ('Is_actual', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Case',
                'ordering': ['-Date'],
                'unique_together': {('Date', 'Reference_ID', 'Is_actual')},
            },
        ),
    ]
